### ISSUE TITLE
Problem running CPM

### ISSUE THREAD

**Issue by paawanpoudel** [amitfrish/scBio#10]
Hi Amit, 

I am trying to run CPM package using my data. I have a single cell data matrix of 2000 genes X 4645 cells also the associated class labels and the tsne projections for the 4645 cells. I am using this data to perform the deconvolution of bulk tumour data consisting of 2000 genes X 100 samples. When this data is used as an input, the CPM methods return following error:

1] "Selecting cells for each iteration"
[1] "Number of iteration: 4410"
[1] "Running CPM, this may take a few minutes"
  |=====================================================================================================================| 100%Error in { : task 2 failed - "incorrect number of subscripts on matrix"

I am not sure why I am getting this error message. Any input from you will be much appreciated. 

Many Thanks,
Pawan

**Comment by amitfrish** [comment]
Hey Pawan,
Sorry for the delay, I somehow missed your issue.
Can you please check the classes of each one of the inputs? Try to make these identical to the classes of the example we provided.
Can you also provide a table of the labels? I want to know how many of each cell type you have in your data. Maybe the default parameters are not relevant to your data.

I hope to solve your problem soon,
Amit
