### ISSUE TITLE
Format of data

### ISSUE THREAD

**Issue by FrederickClasen** [amitfrish/scBio#11]
Hi Amit,

Thanks for the great tool!

I want to make sure of two things:
1) Should the genes in the single-cell matrix match those of the bulk data? In other words, should all the genes that is present in the single-cell matrix also be in the bulk matrix and _vice _versa_?
2) Should the labels used for the SCLabels variable be the same as in the test dataset?

Best wishes,
Frederick

**Comment by amitfrish** [comment]
Hey Frederick,
Thank you and I really hope you'll enjoy using it.
1. You should have enough genes in common between the two objects so CPM would find a good selection of markers for each iteration. However, you don't need to make sure that the genes are identical since CPM will automatically focus only on the intersection between the genes.
2. What do you mean the same? The SCLabels are the cell-type identities so it is relevant only to the reference data and not the bulk samples.

I hope this make sense to you,
Amit

**Comment by FrederickClasen** [comment]
Hi Amit,

Thank you for the reply and apologies for the late reply. 

I am getting the following error:

_[1] "Selecting cells for each iteration"
[1] "Number of iteration: 420"
[1] "Running CPM, this may take a few minutes"
  |=================================================================================================================================================| 100%Error in { : task 2 failed - "undefined columns selected"_

So I was wondering whether it might be due to errors in the format of the data. I checked and even when I only use the genes that overlap between the single-cell data and bulk RNA-sequencing data I still get this error. 

With regards to the second point - whether the SCLabels are should be the same as the test dataset - what I meant was should these labels (for example "NK cell" etc) be the same as the test dataset that you give with the package? Or is it fine if one use different labels for this? 

Another question - for the bulk RNA sequencing dataset, should this be raw (expected) unnormalised counts, or library and insert size normalised (TPM or FPKM)?

Thanks again for the great tool!

Best wishes,
Frederick

**Comment by amitfrish** [comment]
Hey Frederick,
You can choose labels as you want, you absolutely don't need to keep my labels.
As for the normalization, we didn't check the effect of read normalization but I believe that you should use the normalized values (TPM and FPKM are okay) and not the raw read counts. In the paper we indeed normalized the reads by the library size.
Can you attach the dimensions and classes of each input (using the length/dim and class functions, respectively). Also, please add the value for each parameter you used for the analysis.

Amit
