### ISSUE TITLE
how to inffer the cell states from bulk transcriptome data

### ISSUE THREAD

**Issue by guozihuaa** [amitfrish/scBio#13]
the Cell Population Mapping (CPM)  algorithm is really good, but I do not find the way to predict cell states from bulk transcriptome data. I checked the output of the function `CPM`,  but it seem the output **ONLY** include the cell types rather than cell states. Do I miss something?

**Comment by amitfrish** [comment]
Hey, sorry for the delay in my response. 
The "predicted" output within the object returned by CPM is the value for each cell within each sample, taking into account its neighborhood cells. Considering each cell as a state in the space, you get the cell state composition. You can then look for specific states (for example, by aggregating several cells with high proximity in the space).
Tell me if this makes sense to you.

**Comment by guozihuaa** [comment]
thank you, it is clear now
