### ISSUE TITLE
Could you share your original data in your paper?

### ISSUE THREAD

**Issue by HiBearME** [amitfrish/scBio#14]
I have read your paper on nature method and I want to follow you research, however I notice that the dataset in your package is not coincide with the dataset in your paper. Whether if you could add the preprocessed RNA-seq counts profile analyzed in your paper into your package data:

1860 single cells RNA-seq counts profile of infected mice and 2075 of uninfected mice.
38 bulk RNA-seq counts profile of infected mice and 34 of PBS mice.
5 bulk RNA-seq counts profile of untreated CC mice and 1 of C57BL/6J untreated mouse.

They may be filtered by the same gene, and better not to be normalized, but remained as original counts profile.

Any help is appreciated.
:)

.

**Comment by amitfrish** [comment]
Hey,
All the data used in the paper was stored on GEO:
Single cell data: GSE107947
Bulk data: GSE113530 and GSE117975
Good luck with your project and I hope you'll enjoy using CPM :)

**Comment by HiBearME** [comment]
Thanks a lot.
:)
