### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YiHsunSu** [amitfrish/scBio#17]
Hi Amit,

I am trying to run CPM package using my data. When my data is used as an input, the CPM methods return following error:

resAbs = CPM(SCFluAbs, SCLabels, d, SCCellSpace, quantifyTypes = T, typeTransformation = T, no_cores = 6)
[1] "Model size was switched to: 8"
[1] "Selecting cells for each iteration"
[1] "Number of iteration: 1040"
[1] "Running CPM, this may take a few minutes"
  |=======================================================================================================================| 100%Error in { : 
  task 2 failed - "Data object doesn't contain numeric expression values"
> class(d)
[1] "data.frame"
> class(d[2,2])
[1] "numeric"
> class(d[3,3])
[1] "numeric"

I am not sure why I am getting this error message. Any input from you will be much appreciated.

Many Thanks,
Elsa

**Comment by amitfrish** [comment]
Hey Elsa,
Can you please post also the dimensions of all your inputs?

Amit

**Comment by YiHsunSu** [comment]
> Hey Elsa,
> Can you please post also the dimensions of all your inputs?
> 
> Amit

Hi Amit,

Thank you for your reply.

resAbs = CPM(SCFluAbs, SCLabels, d, SCCellSpace, quantifyTypes = T, typeTransformation = T, no_cores = 6)

The dimensions of all my inputs are as follows:
d: 19126 obs. of 502 variables
SCFluAbs: 1858 obs. of 349 variables
SCLabels:  chr [1:349]
SCCellSpace: num [1:349,1:2]


Also, could you please tell me where I can download human data for SCFluAbs, SCLabels and SCCellSpace?  
 

Cheers,
Elsa

**Comment by amitfrish** [comment]
So you are using my example files for your data?
It is not the way you should do it.
My example files are just a small part of the full data and it is specifically for the Lungs in mice. 
If your data is from humans, the gene names and profiles won't match what you have in your data so it should not work.

Is this the case?

**Comment by YiHsunSu** [comment]
Yes, that is the case.

If I want to run my human data, what is your suggestion? download human data for SCFluAbs, SCLabels and SCCellSpace?

**Comment by amitfrish** [comment]
Yes, you need a single cell reference data that is the most suitable for your bulk RNA-seq data. You can get the labels and the space directly from that data.
