### ISSUE TITLE
Where can I find the processed data?

### ISSUE THREAD

**Issue by jesusdfc** [amitfrish/scBio#19]
Hello!

I have read your method and I have seen that the preprocessed data are available at:

Single cell data: GSE107947
Bulk data: GSE113530 and GSE117975

However, I cant find the processed data, where the cell-types are annotated. (Basicly the data(SCFlu) but will all the cells, not just the 349 that are available at the scBio package)

Could you share those files? 

Thanks in advance.

**Comment by amitfrish** [comment]
I sent the file by email
