### ISSUE TITLE
task 1 failed - "'names' attribute [270] must be the same length as the vector [266]"

### ISSUE THREAD

**Issue by ZhaoxiangSimonCai** [amitfrish/scBio#3]
Hi,

I keep getting the error with the stacktrace below:
5.
stop(simpleError(msg, call = expr))
4.
e$fun(obj, substitute(ex), parent.frame(), e$data)
3.
foreach::foreach(runNumber = 1:numOfRuns, .options.snow = opts) %dopar2% { completeSpecificRefBefore = createSpecificRef(refferenceSmaller, modelSize, neighborhoodSize, genePercents, chosenCellList[[runNumber]], ...
2.
CPMMain(SCData, SCLabels, BulkData, cellSelectionList, cellNeigSelectionList, numOfRunsToUse, modelSize, neighborhoodSize, no_cores, genePercents, quantifyTypes, typeTransformation, calculateCI)
1.
CPM(SCRef.log.2k, SCSeg.2k, BulkRNA, SCTsneSpace.2k, quantifyTypes = F, modelSize = 50, minSelection = 4, no_cores = 20)

I'm not an R expert, but I have tried checking the input to make sure column and row names all look good.
Any hint on why this could be happening?

Many thanks in advance.

**Comment by Olimon660** [comment]
Is it that the cell names (column names) have to follow the pattern <label_name>**_**<cell_id>?

**Comment by ZhaoxiangSimonCai** [comment]
I think I figured out already. It seems to happen when the number of cells of a cell type is less than the neighborhoodSize. In my case my data has a group of 6 cells which is less than the default neighborhoodSize=10

It would be worth adding a validation around this and report proper error messages.

**Comment by shayanhoss** [comment]
I was having the same error arise as well but think I fixed it by reducing the model or neighborhood size

**Comment by amitfrish** [comment]
Thank you all for your comments.
CPM was intended for cell types with a cell space that represents the variance in cells within this cell type. In the time that most single cell dataset contains thousands of cell, we simply didn't think this will be a problem. In the manuscript we emphasized that cells should have a proper neighborhood structure and we removed outlayers before applying the algorithm. Of course that this is not possible with 6 cells. I will add a comment for the parameters about this issue on the next update.

**Comment by amitfrish** [comment]
In general, you want your model to be quite small (not above 50) so the regression in each iteration will be informative. However, using small single cell datasets, a model of 50 might choose most of the cells in each iteration and this is also not good (you want many weak learners). 
The same is for the neighborhood size. In dense cell spaces, large neighborhoods make sense since you will get more robust results. However, when your cell space is sparse there aren't many cells in the same neighborhood so this should be lower than the default value.

**Comment by ZhaoxiangSimonCai** [comment]
> Thank you all for your comments.
> CPM was intended for cell types with a cell space that represents the variance in cells within this cell type. In the time that most single cell dataset contains thousands of cell, we simply didn't think this will be a problem. In the manuscript we emphasized that cells should have a proper neighborhood structure and we removed outlayers before applying the algorithm. Of course that this is not possible with 6 cells. I will add a comment for the parameters about this issue on the next update.

Thanks. I was running CPM on a large dataset, so I decided to sample some cells first, which unfortunately resulted in a cell type with 6 cells. Adding a comment (or even better an if statement to validate) will definitely help a lot in the future! Great work!

**Comment by amitfrish** [comment]
Thank you. Added some important notes about this subject in the package information here.
