### ISSUE TITLE
scBio in conda

### ISSUE THREAD

**Issue by favilaco** [amitfrish/scBio#7]
Hi,

Would it be possible for you to deposit scBio in conda-forge / bioconda ?

Best,

Francisco

**Comment by amitfrish** [comment]
Isn't it just for python packages?

**Comment by amitfrish** [comment]
Why is it better than CRAN? In my opinion, it is very easy to install and use it from CRAN.

**Comment by favilaco** [comment]
Of course CRAN is great already!  However, If it was also available in bioconda/conda-forge, it could be directly used within snakemake/nextflow pipelines (avoiding problems with dependencies and so on, allowing more reproducible pipelines).

**Comment by amitfrish** [comment]
Okay. Seems like a nice idea.
I'll try to add this function as soon as I could.

**Comment by favilaco** [comment]
Great! Thanks a lot! :)
